export const mockJobs = [
  {
    id: 1,
    type: "bne",
    title: "TERAPEUTA OCUPACIONAL",
    company: "Confidencial",
    location: "La Araucanía - Temuco",
    description:
      "Promover la inclusión de personas en situación de discapacidad y/o vulnerabilidad social en el mercado laboral, a través de la atención, orientación y evaluación...",
    fullDescription:
      "Promover la inclusión de personas en situación de discapacidad y/o vulnerabilidad social en el mercado laboral, a través de la atención, orientación y evaluación de competencias laborales. Realizar intervenciones terapéuticas ocupacionales individuales y grupales.",
    publishedDate: "2025-01-30",
    salary: null,
    workSchedule: "completa",
    contractType: "indefinido",
    region: "la-araucania",
    educationLevel: "Educación superior completa",
    experience: "2 años mínimo",
    jobLevel: "Profesional",
    economicActivity: "Servicios de salud y asistencia social",
    companyDescription: "Organización dedicada a la inclusión laboral de personas con discapacidad",
    origin: "BNE",
    isPractice: false,
  },
  {
    id: 2,
    type: "bne",
    title: "Administrativo RRHH",
    company: "REPORT LTDA",
    location: "Bío Bío - Talcahuano",
    description:
      "Profesional que realizará funciones acorde con el cargo relacionadas con el área de RRHH, integrará un área consolidada.",
    fullDescription:
      "Profesional que realizará funciones acorde con el cargo relacionadas con el área de RRHH, integrará un área consolidada. Responsabilidades incluyen gestión de personal, nóminas, reclutamiento y selección.",
    publishedDate: "2025-01-29",
    salary: 650000,
    workSchedule: "completa",
    contractType: "indefinido",
    region: "bio-bio",
    educationLevel: "Educación superior completa",
    experience: "1 año mínimo",
    jobLevel: "Ejecutivo",
    economicActivity: "Servicios administrativos y de apoyo",
    companyDescription: "Empresa de servicios administrativos",
    origin: "BNE",
    isPractice: false,
  },
  {
    id: 3,
    type: "bne",
    title: "EJECUTIVO/A DE VENTAS CANAL RETAIL Y DIRECTO",
    company: "Confidencial",
    location: "Bío Bío - Cabrero",
    description:
      "Empresa líder en soluciones constructivas con paneles SIP, está en búsqueda de un/a Ejecutivo/a de Ventas que se integre a nuestro equipo comercial para atender y potenciar el canal...",
    fullDescription:
      "Empresa líder en soluciones constructivas con paneles SIP, está en búsqueda de un/a Ejecutivo/a de Ventas que se integre a nuestro equipo comercial para atender y potenciar el canal retail y directo. Responsable de desarrollar y mantener relaciones comerciales.",
    publishedDate: "2025-01-29",
    salary: 800000,
    workSchedule: "completa",
    contractType: "indefinido",
    region: "bio-bio",
    educationLevel: "Educación media completa",
    experience: "2 años mínimo",
    jobLevel: "Ejecutivo",
    economicActivity: "Construcción",
    companyDescription: "Empresa líder en soluciones constructivas",
    origin: "BNE",
    isPractice: false,
  },
  {
    id: 4,
    type: "bne",
    title: "RELATOR (A) CURSO COMERCIO ELECTRONICO",
    company: "ALTAEXPERTICIA",
    location: "La Araucanía - Curarrehue",
    description:
      "Para curso a realizarse en la Comuna de Curarrehue, se requiere contratar profesional para realizar relatorías enfocadas en potenciar y fomentar la realización de ventas por medios digitales...",
    fullDescription:
      "Para curso a realizarse en la Comuna de Curarrehue, se requiere contratar profesional para realizar relatorías enfocadas en potenciar y fomentar la realización de ventas por medios digitales y plataformas de comercio electrónico.",
    publishedDate: "2025-01-28",
    salary: 450000,
    workSchedule: "parcial",
    contractType: "honorarios",
    region: "la-araucania",
    educationLevel: "Educación superior completa",
    experience: "3 años mínimo",
    jobLevel: "Profesional",
    economicActivity: "Educación",
    companyDescription: "Empresa de capacitación y consultoría",
    origin: "BNE",
    isPractice: false,
  },
  {
    id: 5,
    type: "bne",
    title: "Supervisor de Bodega",
    company: "Confidencial",
    location: "Bío Bío - Talcahuano",
    description:
      "Nuestro Cliente, Importante Empresa del sector industrial ubicado en la comuna de Talcahuano. Requiere a un Supervisor de Bodega para cubrir Reemplazo de Licencia Médica (6 meses)",
    fullDescription:
      "Nuestro Cliente, Importante Empresa del sector industrial ubicado en la comuna de Talcahuano. Requiere a un Supervisor de Bodega para cubrir Reemplazo de Licencia Médica (6 meses). Funciones: supervisión de inventarios, control de stock, gestión de personal.",
    publishedDate: "2025-01-28",
    salary: 750000,
    workSchedule: "completa",
    contractType: "plazo-fijo",
    region: "bio-bio",
    educationLevel: "Educación media completa",
    experience: "2 años mínimo",
    jobLevel: "Supervisor",
    economicActivity: "Industria manufacturera",
    companyDescription: "Empresa del sector industrial",
    origin: "BNE",
    isPractice: false,
  },
  // External jobs
  {
    id: 6,
    type: "external",
    title: "Apilador eléctrico (Operario con Licencia)",
    company: "Thompson Consulting",
    location: "Chile, R.Metropolitana, Santiago - Pudahuel",
    description: "Operario con experiencia en manejo de apilador eléctrico para trabajos de almacén y logística.",
    fullDescription:
      "Se requiere operario con licencia para manejo de apilador eléctrico. Experiencia mínima de 1 año en trabajos de almacén y logística. Conocimientos en normas de seguridad.",
    publishedDate: "2025-01-30",
    salary: 716000,
    workSchedule: "completa",
    contractType: "indefinido",
    region: "metropolitana",
    educationLevel: "Educación media completa",
    experience: "1 año mínimo",
    jobLevel: "Operario",
    economicActivity: "Almacén / Logística / Transporte",
    companyDescription: "Empresa de consultoría en recursos humanos",
    origin: "API",
    isPractice: false,
    publisher: "SherlockHR",
  },
  {
    id: 7,
    type: "external",
    title: "Ejecutivos Call Center 30 hrs. escoge tú horario",
    company: "Grupo Konecta Chile",
    location: "Chile, R.Metropolitana, Santiago - Macul",
    description: "Ejecutivos de call center con jornada de 30 horas semanales, con flexibilidad horaria.",
    fullDescription:
      "Buscamos ejecutivos para call center con jornada de 30 horas semanales. Ofrecemos flexibilidad horaria para que puedas elegir tu turno. Capacitación incluida.",
    publishedDate: "2025-01-30",
    salary: null,
    workSchedule: "parcial",
    contractType: "indefinido",
    region: "metropolitana",
    educationLevel: "Educación media completa",
    experience: "No requerida",
    jobLevel: "Ejecutivo",
    economicActivity: "CallCenter / Telemercadeo",
    companyDescription: "Empresa líder en servicios de contact center",
    origin: "API",
    isPractice: false,
    publisher: "SherlockHR",
  },
  {
    id: 8,
    type: "external",
    title: "Administrador de contratos (Minería) Antofagasta",
    company: "Team-Work",
    location: "Chile, Antofagasta, Antofagasta",
    description: "Administrador de contratos para el sector minero en la región de Antofagasta.",
    fullDescription:
      "Se requiere administrador de contratos con experiencia en el sector minero. Responsable de la gestión y administración de contratos de servicios y suministros.",
    publishedDate: "2025-01-30",
    salary: null,
    workSchedule: "completa",
    contractType: "indefinido",
    region: "antofagasta",
    educationLevel: "Educación superior completa",
    experience: "3 años mínimo",
    jobLevel: "Profesional",
    economicActivity: "Minería",
    companyDescription: "Empresa de servicios de recursos humanos",
    origin: "API",
    isPractice: false,
    publisher: "SherlockHR",
  },
  {
    id: 9,
    type: "external",
    title: "Administrativo Crédito y Cobranza / Belloto",
    company: "Colun",
    location: "Viña del Mar, Valparaíso",
    description: "Administrativo para el área de crédito y cobranza en planta Belloto.",
    fullDescription:
      "Buscamos administrativo para el área de crédito y cobranza. Funciones incluyen gestión de cartera, seguimiento de pagos y atención a clientes.",
    publishedDate: "2025-01-30",
    salary: null,
    workSchedule: "completa",
    contractType: "indefinido",
    region: "valparaiso",
    educationLevel: "Educación superior incompleta",
    experience: "1 año mínimo",
    jobLevel: "Administrativo",
    economicActivity: "Alimentos",
    companyDescription: "Cooperativa láctea líder en Chile",
    origin: "API",
    isPractice: false,
    publisher: "AIRA",
  },
  {
    id: 10,
    type: "external",
    title: "captador de ventas planes moviles en terreno Iquique",
    company: "Confidencial",
    location: "Tarapacá, Iquique",
    description:
      "Captar clientes para la venta de planes de telefonía móvil en terreno, media jornada AM o PM preferentemente.",
    fullDescription:
      "Captar clientes para la venta de planes de telefonía móvil en terreno, media jornada AM o PM preferentemente. Se ofrece capacitación, sueldo base, incentivos diarios, bono por cumplimiento de meta mensual, apoyo constante de un supervisor.",
    publishedDate: "2025-01-30",
    salary: 529000,
    workSchedule: "parcial",
    contractType: "indiferente",
    region: "tarapaca",
    educationLevel: "No requerida",
    experience: "No requerida",
    jobLevel: "Ejecutivo",
    economicActivity: "Venta al por menor de otros productos en comercios especializados n.c.p.",
    companyDescription: "Ventas de planes de telefonía celular y fibra óptica",
    origin: "API",
    isPractice: false,
  },
]
