# ==========================
# Configuración base de datos H2 (en memoria)
# ==========================
spring.datasource.url=jdbc:h2:mem:postulacionesdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ==========================
# JPA / Hibernate
# ==========================
# Genera automáticamente las tablas según tus entidades
spring.jpa.hibernate.ddl-auto=update

# No mostrar las consultas SQL en consola
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Silenciar también los valores de los parámetros
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=ERROR

# ==========================
# Consola H2 (para ver la BD desde navegador)
# ==========================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
