# App
spring.application.name=postulaciones-service
server.port=8080

spring.profiles.active=dev

# H2 en dev (ajústalo si usas SQL Server)
spring.datasource.url=jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;MODE=MSSQLServer;DATABASE_TO_UPPER=false
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate (dev)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

# Swagger / OpenAPI (springdoc)
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger

# JWT (secreto >= 32 chars; solo dev)
security.jwt.secret=cambia-este-secreto-de-mas-de-32-caracteres-por-favor-1234567890
security.jwt.expirationMs=3600000

# (Opcional) desactiva flyway si no tienes migraciones aún
# spring.flyway.enabled=false

